name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest test_pessoa_routes.py

  build-and-push-image:
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t "${{ secrets.DOCKERHUB_USERNAME }}"/pessoa:latest .
        docker push "${{ secrets.DOCKERHUB_USERNAME }}"/pessoa:latest

  run-mysql-and-app:
    runs-on: ubuntu-latest

    needs: test

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: pessoa
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Wait for MySQL to be ready
      run: sleep 20s

    - name: Set up Docker Compose
      run: docker-compose -f docker-compose.yml up --detach

    - name: Run database migrations
      run: |
        docker-compose exec web python manage.py migrate

    - name: Clean up Docker Compose
      run: docker-compose -f docker-compose.yml down
